name: hwe
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.8

  # Core scientific stack
  - numpy=1.23.5
  - pandas
  - scipy
  - scikit-learn
  - numba

  # Visualization / notebooks
  - matplotlib
  - seaborn
  - jupyterlab
  - ipywidgets
  - tqdm
  - openpyxl

  # ML / Optimization
  - pytorch
  - tensorflow
  - cvxopt
  - cvxpy
  - osqp
  - statsmodels

  # pip bridge
  - pip

  # pip-only dependencies
  - pip:
      - git+https://github.com/dcuoliveira/nphc
